project:
  type: website
  output-dir: .

website:
  title: "junhao241"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: true
  warning: false
  message: false
